"""add client id in subs table

Revision ID: 0f53c68a4dcf
Revises: ae93e4a96e10
Create Date: 2026-03-10 18:08:40.652800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f53c68a4dcf'
down_revision: Union[str, None] = 'ae93e4a96e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('client_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'client_id')
    # ### end Alembic commands ###
